add bandit and safety checks

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,7 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install flake8 flake8-black pytest pytest-custom_exit_code black isort mypy
+        pip install flake8 flake8-black pytest pytest-custom_exit_code black isort bandit safety mypy
         pip install -e .[all]
     - name: Lint with flake8
       run: flake8 .
@@ -30,7 +30,12 @@ jobs:
       run: black --check .
     - name: Run isort --check-only .
       run: isort --check-only --profile=black .
-    - name: Check types
-      run: mypy .
+    - name: Run bandit
+      run: bandit -c .bandit -r .
+    - name: Run Safety
+      # there is no allow-failure yet. see https://github.com/actions/toolkit/issues/399
+      run: safety check || true
     - name: pytest
       run: pytest .
+    - name: Check types
+      run: mypy .
